[project]
name = "Et In Arcadia Ego"
project_name = "arcadia"
version = "1.0.0"
description = "I too was in Arcadia."
author_name = "Nicolas Poussin"
author_email = "nicolas@poussin.edu"
github_username = "arcadia"
license = "MIT"
keywords = ["nockapp", "nockchain", "hoon"]
nockapp_commit_hash = "336f744b6b83448ec2b86473a3dec29b15858999"
template = "basic"
