manifest-version = "1"
date = "2025-11-01"

[pkg.hoonc]
version = "0.2.0"
components = ["core"]

[pkg.hoonc.target.aarch64-apple-darwin]
available = true
url = "https://github.com/sigilante/nockchain/releases/download/stable-build-a3d1508fdb4ca151bd3d4c3809b1d20725620e25/hoonc-stable-0.2.0-aarch64-apple-darwin.tar.gz"
hash_blake3 = "41bf155d88a6d4a3b0e6a8eefc8d3d982393c26f5ee0c57a42cc2f7c48c0e9e0"
hash_sha1 = "701a89f42e3539e164432593170b13a3df6eb2a3"
