manifest-version = "1"
date = "2025-11-01"

[pkg.hoonc]
version = "0.2.0"
components = ["core"]

[pkg.hoonc.target.x86_64-unknown-linux-gnu]
available = true
url = "https://github.com/sigilante/nockchain/releases/download/stable-build-a3d1508fdb4ca151bd3d4c3809b1d20725620e25/hoonc-stable-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
hash_blake3 = "9cfe842c2219559f666ced23ab0dcdc3a1d66143a7c68e695a0d16077fc84c29"
hash_sha1 = "51bc271b07ece84aee15969dbb5bc9a08445c8ac"
