manifest-version = "1"
date = "2025-11-01"

[pkg.hoon]
version = "0.1.0"
components = ["core"]

[pkg.hoon.target.x86_64-unknown-linux-gnu]
available = true
url = "https://github.com/sigilante/nockchain/releases/download/stable-build-a3d1508fdb4ca151bd3d4c3809b1d20725620e25/hoon-stable-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
hash_blake3 = "81f43d91e2998ffff20b9a51e4c401ffca22cea2a6a095da65d20cff7fe8edc6"
hash_sha1 = "cae207c16e7752be668f6aedcc313c2652320a6b"
