manifest-version = "1"
date = "2025-11-01"

[pkg.nockup]
version = "0.3.0"
components = ["core"]

[pkg.nockup.target.x86_64-unknown-linux-gnu]
available = true
url = "https://github.com/sigilante/nockchain/releases/download/stable-build-a3d1508fdb4ca151bd3d4c3809b1d20725620e25/nockup-stable-0.3.0-x86_64-unknown-linux-gnu.tar.gz"
hash_blake3 = "445517ca2d33568347afd2fcd2e3ff9256484916790b448dd7355459ac0e15ff"
hash_sha1 = "1b02c58fe7bd21f72b875b5714b7cccef3c54a0a"
